/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_4 (
    input [1:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sum
  );
  
  
  
  always @* begin
    sum = 16'h0000;
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
      end
      2'h1: begin
        sum = a - b;
      end
      2'h2: begin
        sum = a * b;
      end
    endcase
  end
endmodule
