/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_4 (
    input [1:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sum,
    output reg [0:0] z,
    output reg [0:0] v,
    output reg [0:0] n
  );
  
  
  
  reg [15:0] ans;
  
  reg [15:0] xb;
  
  always @* begin
    ans = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        ans = a + b;
      end
      2'h1: begin
        ans = a - b;
      end
      2'h2: begin
        ans = a * b;
      end
    endcase
    sum = ans;
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    z = (ans == 1'h0);
    xb = b ^ (5'h10 * alufn[0+0-:1]);
    v = (|{(&{a[15+0-:1], xb[15+0-:1], ~ans[15+0-:1]}), (&{~a[15+0-:1], ~xb[15+0-:1], ans[15+0-:1]})});
    n = ans[15+0-:1];
  end
endmodule
