/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_3 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out,
    output reg [0:0] z,
    output reg [0:0] v,
    output reg [0:0] n
  );
  
  
  
  wire [16-1:0] M_adder_sum;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  reg [2-1:0] M_adder_alufn;
  adder_4 adder (
    .a(a),
    .b(b),
    .alufn(M_adder_alufn),
    .sum(M_adder_sum),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n)
  );
  wire [16-1:0] M_boolean_out;
  reg [4-1:0] M_boolean_alufn;
  boolean_5 boolean (
    .a(a),
    .b(b),
    .alufn(M_boolean_alufn),
    .out(M_boolean_out)
  );
  wire [16-1:0] M_compare_cmp;
  reg [2-1:0] M_compare_alufn;
  compare_6 compare (
    .a(a),
    .b(b),
    .alufn(M_compare_alufn),
    .cmp(M_compare_cmp)
  );
  wire [16-1:0] M_shifter_ashifted;
  reg [2-1:0] M_shifter_alufn;
  shifter_7 shifter (
    .a(a),
    .b(b),
    .alufn(M_shifter_alufn),
    .ashifted(M_shifter_ashifted)
  );
  
  always @* begin
    out = 1'h0;
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    M_adder_alufn = alufn[0+1-:2];
    M_boolean_alufn = alufn[0+3-:4];
    M_compare_alufn = alufn[1+1-:2];
    M_shifter_alufn = alufn[0+1-:2];
    
    case (alufn[4+1-:2])
      2'h0: begin
        out = M_adder_sum;
        z = M_adder_z;
        v = M_adder_v;
        n = M_adder_n;
      end
      2'h1: begin
        out = M_boolean_out;
      end
      2'h2: begin
        out = M_shifter_ashifted;
      end
      2'h3: begin
        out = M_compare_cmp;
      end
    endcase
  end
endmodule
