/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_5 (
    input [3:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  integer i;
  
  always @* begin
    out = 16'h0000;
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      
      case (alufn[0+3-:4])
        4'h8: begin
          out[(i)*1+0-:1] = a[(i)*1+0-:1] & b[(i)*1+0-:1];
        end
        4'h7: begin
          out[(i)*1+0-:1] = ~(a[(i)*1+0-:1] & b[(i)*1+0-:1]);
        end
        4'he: begin
          out[(i)*1+0-:1] = a[(i)*1+0-:1] | b[(i)*1+0-:1];
        end
        4'h1: begin
          out[(i)*1+0-:1] = ~(a[(i)*1+0-:1] | b[(i)*1+0-:1]);
        end
        4'h6: begin
          out[(i)*1+0-:1] = a[(i)*1+0-:1] ^ b[(i)*1+0-:1];
        end
        4'h9: begin
          out[(i)*1+0-:1] = ~(a[(i)*1+0-:1] ^ b[(i)*1+0-:1]);
        end
        4'ha: begin
          out[(i)*1+0-:1] = a[(i)*1+0-:1];
        end
        4'h5: begin
          out[(i)*1+0-:1] = ~a[(i)*1+0-:1];
        end
      endcase
    end
  end
endmodule
