/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_6 (
    input [15:0] a,
    input [15:0] b,
    input [1:0] alufn,
    output reg [15:0] cmp
  );
  
  
  
  always @* begin
    cmp = 16'h0000;
    
    case (alufn)
      2'h1: begin
        cmp[0+0-:1] = a == b;
      end
      2'h2: begin
        cmp[0+0-:1] = a < b;
      end
      2'h3: begin
        cmp[0+0-:1] = a <= b;
      end
    endcase
  end
endmodule
